# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfenvgo < Formula
  desc "Terraform version manager written in Go"
  homepage "https://github.com/dmakeienko/tfenvgo"
  version "2.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dmakeienko/tfenvgo/releases/download/v2.0.1/tfenvgo_2.0.1_darwin_amd64.tar.gz"
      sha256 "40bbc1c860af9f67edb8a241c861e4bc184fda98fb934d5b884cd68d20a6ca86"

      define_method(:install) do
        bin.install "tfenvgo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dmakeienko/tfenvgo/releases/download/v2.0.1/tfenvgo_2.0.1_darwin_arm64.tar.gz"
      sha256 "89307d7358d881a652c0174d480955284d04e26c58fb668242427c823061d080"

      define_method(:install) do
        bin.install "tfenvgo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dmakeienko/tfenvgo/releases/download/v2.0.1/tfenvgo_2.0.1_linux_amd64.tar.gz"
      sha256 "eb9968417b8f107635385db34a5e24f26fdda59c2e7fdf93bfcf5d8d7fbc8cc1"
      define_method(:install) do
        bin.install "tfenvgo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dmakeienko/tfenvgo/releases/download/v2.0.1/tfenvgo_2.0.1_linux_arm64.tar.gz"
      sha256 "0cbe8f91339227ca678b376a1d30f5d7bad69977e5d20ee5467150d6165af711"
      define_method(:install) do
        bin.install "tfenvgo"
      end
    end
  end

  test do
    system "#{bin}/tfenvgo", "--version"
  end
end
