# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfenvgo < Formula
  desc "Terraform version manager written in Go"
  homepage "https://github.com/dmakeienko/tfenvgo"
  version "2.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dmakeienko/tfenvgo/releases/download/v2.0.2/tfenvgo_2.0.2_darwin_amd64.tar.gz"
      sha256 "1055bdc781df3bd14cd3865cf8da6ac408c51bcaafec5c74f38ab250ef2e9594"

      define_method(:install) do
        bin.install "tfenvgo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dmakeienko/tfenvgo/releases/download/v2.0.2/tfenvgo_2.0.2_darwin_arm64.tar.gz"
      sha256 "373f1acde45c682090d9eecf9e2ca97a0a04b0b95a99c79b5320af167675f932"

      define_method(:install) do
        bin.install "tfenvgo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dmakeienko/tfenvgo/releases/download/v2.0.2/tfenvgo_2.0.2_linux_amd64.tar.gz"
      sha256 "82bf794862905c5b9d252b4e3be150bf765d1f8bdc76afa0dfa61111f46a2668"
      define_method(:install) do
        bin.install "tfenvgo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dmakeienko/tfenvgo/releases/download/v2.0.2/tfenvgo_2.0.2_linux_arm64.tar.gz"
      sha256 "e8fa9212bb61cf9d396428fd4d5fe67b540e50143bd556182f9adb3c0bc7f3d0"
      define_method(:install) do
        bin.install "tfenvgo"
      end
    end
  end

  test do
    system "#{bin}/tfenvgo", "--version"
  end
end
